-- ============================================================================
-- Supabase + n8n Vector Store Setup Script
-- Compatible with n8n's "Supabase Vector Store" Node
-- ============================================================================

-- 1. Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Create documents table (matches n8n Supabase Vector Store default)
-- Note: Dimension is set to 768 for Gemini text-embedding-004 / 384 for MiniLM / 1536 for OpenAI.
-- Adjust VECTOR(768) if using an embedding model with different dimensions.
CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    embedding VECTOR(768)
);

-- 3. Create HNSW index for high performance approximate nearest neighbor search
CREATE INDEX IF NOT EXISTS documents_embedding_hnsw_idx 
ON documents 
USING hnsw (embedding vector_cosine_ops);

-- 4. Create GIN index on metadata for fast tenant filtering (student_id, subject_id)
CREATE INDEX IF NOT EXISTS documents_metadata_gin_idx 
ON documents 
USING gin (metadata);

-- 5. Create n8n match_documents RPC function
CREATE OR REPLACE FUNCTION match_documents (
    query_embedding VECTOR(768),
    match_count INT DEFAULT 5,
    filter JSONB DEFAULT '{}'::jsonb
) 
RETURNS TABLE (
    id BIGINT,
    content TEXT,
    metadata JSONB,
    similarity FLOAT
)
LANGUAGE plpgsql
AS $$
#variable_conflict use_column
BEGIN
    RETURN QUERY
    SELECT
        documents.id,
        documents.content,
        documents.metadata,
        1 - (documents.embedding <=> query_embedding) AS similarity
    FROM documents
    WHERE documents.metadata @> filter
    ORDER BY documents.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;
